### ISSUE TITLE
debian cli boot fix

### ISSUE THREAD

**Issue by MaticMorgan** [radxa-build/radxa-cm3-io#11]
I attempted to use the "radxa-cm3-io_debian_bullseye_cli_b27.img.xz" image from the following page:
https://github.com/radxa-build/radxa-cm3-io/releases/tag/b27
The iso doesn't even boot. I did some digging and it said that the panfrost module has to be disabled for the iso to boot.
I inserted the SD card with the above mentioned iso burned to it into a different debian-based computer and ran the following commands:

#mount the SD card
sudo mount /dev/mmcblk0p3 /mnt

#bind mount the necessary filesystems on the SD card
sudo mount --bind /dev /mnt/dev
sudo mount --bind /dev/pts /mnt/dev/pts
sudo mount --bind /proc /mnt/proc
sudo mount --bind /sys /mnt/sys
sudo mount --bind /run /mnt/run

#entering the chroot environment
sudo chroot /mnt /bin/bash

#blacklisting the panfrost module by updating modules.d
echo "blacklist panfrost" > /etc/modprobe.d/blacklist-panfrost.conf

#updating initramfs
update-initramfs -u

exit

#unmounting everything
sudo umount /mnt/dev/pts
sudo umount /mnt/dev
sudo umount /mnt/proc
sudo umount /mnt/sys
sudo umount /mnt/run
sudo umount /mnt

With these fixes the system would boot. I ran the cm3 on the Radxa Taco. I don't have a cm3 IO board to test it there.

I guess this isn't an issue, as much as a fix. I'd love it if the devs would review this and possibly update the debian cli image.

**Comment by RadxaYuntian** [comment]
Unfortunately we have decided to no longer provide CLI images, as our testing capacity is at limit. Currently, we have disabled panfrost on rk356x kernel, so new CLI images built with our toolchains are working out-of-the-box again. However, this prevents us from supporting this driver on RK3528 devices, which use the same kernel...
